spring:
  profiles:
    default: "dev"
    active: "dev"
#  main:
#    banner-mode: "off"

---

server:
  port: 8083

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

oauth-config:
  resource-id: REMOTE_RESOURCES
  client-id: remote-client
  client-secret: admin
  token-endpoint: http://localhost:8081/oauth/check_token

logging:
  level:
    .: error
    org.springframework: DEBUG
    com.oauth2: DEBUG

---

spring:
  profiles: test
server:
  email: test@example.com
  port: 8084
  # Add test configs

---

spring:
  profiles: stage
server:
  email: stage@example.com
  port: 8085
  # Add stage configs

---

spring:
  profiles: prod
server:
  email: prod@example.com
  port: 8006
  # Add production configs
